name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_PATH }}
            git pull origin main
            npm install --omit=dev
            npm run build
            pm2 restart connection.ae-production
          EOF
          rm -f private_key.pem
